server:
  #  address:
  port: 8081
  servlet:
    context-path: /security

spring:
  application: security
  # 数据库
  datasource:
    url: jdbc:mysql://172.28.19.88:3306/cltest?useSSL=false
    username: dhome
    password: dhome
    driver-class-name: com.mysql.jdbc.Driver
  # redis
  redis:
    password: redis_dhome
    cluster:
      max-redirects: 5
      nodes:
      - 172.28.19.80:6380
      - 172.28.19.80:6381
      - 172.28.19.85:6380
      - 172.28.19.85:6381
      - 172.28.19.89:6380
      - 172.28.19.89:6381
    jedis:
      pool:
        max-active: 50
        max-idle: 40
        max-wait: 1000ms
        min-idle: 15
    timeout: 1000ms
#Mybatis Config
mybatis:
  typeAliasesPackage: com.security.demo.dao
  mapperLocations: classpath:mybatis/**/*.xml
logging:
  level:
    com.security.demo: debug
